-- Values for the languages table.
INSERT INTO languages VALUES (0, 'ja');
INSERT INTO languages VALUES (1, 'roomaji');
INSERT INTO languages VALUES (2, 'ko');
INSERT INTO languages VALUES (3, 'zh');
INSERT INTO languages VALUES (4, 'fr');
INSERT INTO languages VALUES (5, 'de');
INSERT INTO languages VALUES (6, 'es');
INSERT INTO languages VALUES (7, 'it');
INSERT INTO languages VALUES (8, 'en');
INSERT INTO languages VALUES (9, 'cs');
INSERT INTO languages VALUES (10, 'ja-kanji');
